language: python
python:
  - "3.4"
  - "3.5"

cache: pip

# command to install dependencies
install: "pip install -r requirements.txt"

# command to run tests
script: py.test --splinter-webdriver phantomjs