# Generated by Django 2.2.5 on 2019-09-30 09:57

import dispatch_service.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch_service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='redirect',
            name='redirect_from',
            field=models.CharField(help_text='Eg.: <b>buy/qabel-pro-x</b> would make the resulting link <i>https://accounting.qabel.org/dispatch/buy/qabel-pro-x/</i>', max_length=200, primary_key=True, serialize=False, validators=[dispatch_service.models.validate_redirect_from]),
        ),
    ]
