# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-11 08:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qabel_provider', '0008_auto_20160310_1238'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='is_confirmed',
        ),
    ]
