# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-14 21:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qabel_provider', '0009_remove_profile_is_confirmed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='downloads',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='quota',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='used_storage',
        ),
    ]
