# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-01 09:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qabel_provider', '0010_remove_profile_is_disabled'),
        ('qabel_provider', '0010_auto_20160314_2125'),
    ]

    operations = [
    ]
