# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-10 12:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qabel_provider', '0011_merge'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='block_quota',
            field=models.IntegerField(default=2147483648, verbose_name='block server quota (in bytes)'),
        ),
    ]
