# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-10 12:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qabel_provider', '0012_profile_block_quota'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='monthly_traffic_quota',
            field=models.BigIntegerField(default=21474836480, verbose_name='block server traffic quota per month (in bytes)'),
        ),
    ]
