# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-10 14:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qabel_provider', '0013_profile_monthly_traffic_quota'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='block_quota',
            field=models.BigIntegerField(default=2147483648, verbose_name='block server quota (in bytes)'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='monthly_traffic_quota',
            field=models.BigIntegerField(default=21474836480, verbose_name='block server traffic quota per month (in bytes)'),
        ),
    ]
